// SPDX-License-Identifier: AGPL-3.0-only
import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {createHash} from 'node:crypto';import {root,validate,markdown} from '../scripts/catalogue.mjs';
const bytes=await readFile(root+'data/free-tokens.json'),data=JSON.parse(bytes),manifest=JSON.parse(await readFile(root+'data/MANIFEST.json'));
const checked=d=>{const b=Buffer.from(JSON.stringify(d));return validate(d,b,{...manifest,bytes:b.length,sha256:createHash('sha256').update(b).digest('hex')});};
test('pinned complete snapshot',()=>assert.equal(validate(data,bytes,manifest).official,73));
test('reject changed body',()=>assert.throws(()=>validate(data,Buffer.concat([bytes,Buffer.from(' ')]),manifest)));
test('reject duplicate identity',()=>{const d=structuredClone(data);d.offers[0].id=d.officialOffers[0].id;assert.throws(()=>checked(d),/Structured|duplicate/);});
test('reject dropped payment condition field',()=>{const d=structuredClone(data);delete d.offers[0].requiresPayment;assert.throws(()=>checked(d),/Structured|payment/);});
test('reject unsafe evidence URL',()=>{const d=structuredClone(data);d.officialOffers[0].evidence[0].url='javascript:alert(1)';assert.throws(()=>checked(d),/Structured|Unsafe/);});
test('Markdown retains every exact record',()=>{const m=markdown(data);for(const o of [...data.officialOffers,...data.offers])assert.ok(m.includes(JSON.stringify(o,null,2)));});

test('vendor full statements and excerpts excluded',()=>{for(const o of data.offers){assert.ok(!Object.hasOwn(o,'fullStatement'));for(const e of o.evidence)assert.ok(!Object.hasOwn(e,'excerpt'));}});
test('changed original structured condition rejected',()=>{const d=structuredClone(data);d.offers[0].conditions.pop();assert.throws(()=>checked(d),/Structured/);});
test('derivation pinned per record',()=>{for(const o of data.offers){assert.equal(o.derivedFrom.recordId,o.id);assert.equal(o.derivedFrom.snapshotSha256,data.derivedFrom.sha256);assert.equal(o.derivedFrom.observedAt,o.observedAt);}});
test('hub license text and explicit file map resolve',async()=>{const {readdir}=await import('node:fs/promises');const exportMap=JSON.parse(await readFile(root+'public-export-manifest.json'));const walk=async(dir,prefix='')=>{const paths=[];for(const e of await readdir(dir,{withFileTypes:true})){if(e.name==='.git')continue;const name=prefix+e.name;if(e.isDirectory())paths.push(...await walk(dir+e.name+'/',name+'/'));else paths.push(name);}return paths;};assert.deepEqual(exportMap.files.map(x=>x.path).sort(),(await walk(root)).sort());const license=await readFile(root+'LICENSE','utf8');assert.ok(license.includes('AGPL-3.0-only'));assert.ok(!license.includes('Apache-2.0.txt'));assert.ok((await readFile(root+'LICENSES/AGPL-3.0-only.txt','utf8')).includes('GNU AFFERO GENERAL PUBLIC LICENSE'));for(const name of ['README.md','README.zh-CN.md','DATA-LICENSE.md']){const text=await readFile(root+name,'utf8');for(const match of text.matchAll(/\]\(([^)]+)\)/g)){if(!/^https?:/.test(match[1]))await readFile(root+match[1]);}}});
